#define FONT_COLOR_WHITE       FOREGROUND_RED  | FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define FONT_COLOR_LIGHT_GRAY  FOREGROUND_RED  | FOREGROUND_BLUE | FOREGROUND_GREEN
#define FONT_COLOR_GRAY        FOREGROUND_INTENSITY
#define FONT_COLOR_RED         FOREGROUND_RED
#define FONT_COLOR_LIGHT_RED   FOREGROUND_RED | FOREGROUND_INTENSITY
#define FONT_COLOR_BLUE        FOREGROUND_BLUE
#define FONT_COLOR_LIGHT_BLUE  FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define FONT_COLOR_GREEN       FOREGROUND_GREEN
#define FONT_COLOR_LIGHT_GREEN FOREGROUND_GREEN | FOREGROUND_INTENSITY


#define BACKGROUND_COLOR_WHITE       BACKGROUND_RED  | BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BACKGROUND_COLOR_LIGHT_GRAY  BACKGROUND_RED  | BACKGROUND_BLUE | BACKGROUND_GREEN
#define BACKGROUND_COLOR_GRAY        BACKGROUND_INTENSITY
#define BACKGROUND_COLOR_RED         BACKGROUND_RED
#define BACKGROUND_COLOR_LIGHT_RED   BACKGROUND_RED | FOREGROUND_INTENSITY
#define BACKGROUND_COLOR_BLUE        BACKGROUND_BLUE
#define BACKGROUND_COLOR_LIGHT_BLUE  BACKGROUND_BLUE | FOREGROUND_INTENSITY
#define BACKGROUND_COLOR_GREEN       BACKGROUND_GREEN
#define BACKGROUND_COLOR_LIGHT_GREEN BACKGROUND_GREEN | FOREGROUND_INTENSITY
